### PR TITLE
feat: min field

### PR DESCRIPTION
**Pull request by wingkwong**
- closes: #743 
- things to discuss: migration script / icon

image

### CODE REVIEW

**Review by nichenqin — CHANGES_REQUESTED** [review]
data.sql broken will try to fix

**Comment by nichenqin** [comment]
run `pnpm run db:seed`
image

**Review by WanShufen — CHANGES_REQUESTED** [review]
Here is an issue, and it is recommended to resolve it together 
https://github.com/undb-xyz/undb/issues/1319

**Comment by wingkwong** [comment]
> Here is an issue, and it is recommended to resolve it together #1319

Handled in another PR.

**Review by nichenqin — COMMENTED** [review]
LGTM

**Review by nichenqin — APPROVED** [review]

**Pull request merged**
